sudo: required

services:
    - docker

script:
    - cp docker-compose.yml.dist docker-compose.yml
    - sed -i "s/REPLACE_WITH_YOUR_EMAIL/jeyser-crm.travis@example.com/g" docker-compose.yml
    - docker-compose build > /dev/null # reduce resources consumption as we are reaching travis limits
    # check prod env is working
    - docker-compose up -d
    - docker-compose run --rm web php bin/console doctrine:schema:create
    - docker-compose run --rm web php bin/console doctrine:fixtures:load -n
    - docker-compose run --rm web php bin/console doctrine:schema:validate --ansi
    # Run tests on test env
    - docker-compose exec web vendor/bin/behat ./features/
    - docker-compose stop


