services:
    Mgate.etude_manager:
        class: Mgate\SuiviBundle\Manager\EtudeManager
        arguments:
          - "@doctrine.orm.entity_manager"
          - "@app.json_key_value_store"
          - "@security.authorization_checker"

    Mgate.doctype_manager:
        class: Mgate\SuiviBundle\Manager\DocTypeManager
        arguments:
          - "@doctrine.orm.entity_manager"
    Mgate.chart_manager:
        class: Mgate\SuiviBundle\Manager\ChartManager
        arguments:
          - "@doctrine.orm.entity_manager"
          - "@Mgate.etude_manager"
          - "@logger"
          - "@app.json_key_value_store"
          - "@kernel"

    form.type_extension.help_message:
        class: Mgate\SuiviBundle\Form\Extension\HelpMessageTypeExtension
        tags:
          - { name: form.type_extension, extended_type: Symfony\Component\Form\AbstractTypeExtension}

    Mgate.email_etu:
            class: Mgate\SuiviBundle\Manager\EmailEtuManager
            arguments:
              - "@app.json_key_value_store"

    Mgate.etude_extension:
      class: Mgate\SuiviBundle\Manager\EtudeExtension
      tags:
          - { name: twig.extension }
